### ISSUE TITLE
MicroProfile properties collector throws java.lang.StackOverflowError

### ISSUE THREAD

**Issue by mn-qbasic** [jbosstools/jbosstools-quarkus#237]
Hi!
I'm tyring Quarkus in Eclipse (2023-06) using Quarkus Tools (4.28.0.Final) using Windows 10 + Oracle JDK 17 (Windows 10, 8 GB).

When I change application.properties, apparently triggers a "MicroProfile properties collector" process, and always gives the following error:

    An internal error occurred during: "MicroProfile properties collector".
    java.lang.StackOverflowError

After that, It tries to close Eclipse. It doesn't matter how much RAM I specify in eclipse.ini.

The only workaround I could figure out was disabling Quarkus Application Properties from Language Servers, that is: Windows -> Preferences -> Language Servers -> unclick "Quarkus Application Properties".

Am I missing something? I'm very new to Quarkus and I'm not sure how bad is disabling this feature.
Thanks in advance.
Matt.

**Comment by angelozerr** [comment]
@mn-qbasic as Jboss Tools Quarkus depends from several plugin like wildwebdeveloper and lsp4e we need to align our plugin with those dependencies because today it is badly unusable as you have seen.

@sbouchet is working hard to fix this issue and will try to do à release asap. In other words please be patient.

**Comment by mn-qbasic** [comment]
Thanks @angelozer and @sbouchet!
