### ISSUE TITLE
Code completion also for yaml/yml files

### ISSUE THREAD

**Issue by nimo23** [jbosstools/jbosstools-quarkus#83]
Hello,

Quarkus has support for yaml/yml files. Would be nice to have code completion also within `application.yaml`, `application.yml` like that in `application.properties`. 

Thanks.

**Comment by angelozerr** [comment]
JBossTools Quarus is based on [MicroProfile Language Server](https://github.com/redhat-developer/quarkus-ls) which gives the capability to generate a JSON Schema for the project properties. This JSON Schema can be used by [YAML Language Server](https://github.com/redhat-developer/yaml-language-server). We do that in [vscode-quarkus](https://github.com/redhat-developer/vscode-quarkus) to provide YAML support for application.yaml.

In Eclipse context, [WWD ](https://github.com/eclipse/wildwebdeveloper)should be installed because it provide an eclipse plugin which consumes the YAML Language Server but it requires to provide an extension point to consume the YAML Language Server. I have started something in https://github.com/angelozerr/wildwebdeveloper/tree/yaml-custom-schema but not finished my work yet

**Comment by jeffmaury** [comment]
Fixed by f0218ea4551bbb148341d542765bd9f0800a9bae
